dist: xenial   # required for Python >= 3.7
language: python

stages:
- install
- test
- name: deploy
  if: tag =~ tdvt  # only tags with tdvt will allow deploy

install:
  - pip install -e tdvt/

script:
  - cd tdvt/test && python tdvt_test.py -v CommandLineTest ConfigTest DiffTest PrintConfigurationsTest

jobs:
  include:
   - python: 3.4
   - python: 3.5
   - python: 3.6
   - python: 3.7

   - stage: deploy
     python: 3.4
     script: cd $(bash before_deploy.sh)
     deploy:
     - provider: pypi
       user:
         secure: "Cl0P8yEF+GzM2saBVrCXOLqdBvf05UemsrJB/lW5yDtVRKYHc3OeFwHWRRpCRT7R57NQrrjeLYamhARM4TBG6/qzA1+wyIekarkyvhu16ZwLArng6/3397kgcRiu7FgTZY9G3glpKawAnh4xhjKC3If/O+WlHKFXDC2GdqLRWgdOyrQrL3QECOthXNzvO0ffLvBXzrazSHBQUfY6W4Rb065VjnZaVmwBWJJ7cu14tk7F0Xde2voOXpNryr/U0C7XbwGZ37qnBtw80fxPlpesJYtEj55FhPgELUx+lyl7YGVtifpbR5tp28jp73Pxh+yOBuEAl5gcCDY3npNeIH0RpO8amM9Txpx0uUr2TFkprRva5y1hE3gwkhWjFHPlfETHveWjQKMO+10m1NqtyyDi21j5q/7clfU/rJJm18fp5wf6PP7nSUuX6xA2doxh3z+3JvKJPEovaqlmRtokcr0htgOeYARE5erTg8XXGszQaJZEx52/G6CX60S33XPTXz6I2adpFqLLPNzpcvF99AsQSdbi9mc1xv+EMe+nLwu6m6xSeMpiONF2rhWWr0QdDloZhDVAVvdv9kj6jaC3tcjM5fReb95y/Q9k0PDMSHEQksfgqZP2tDu6un0ukxwtI0RMnXiPlqGBSHdpBJifw9thLQyIO6BjgskdltQq3DPE6Rk="
       password:
         secure: "ry8BAYxVmIm4TuJRUB69TaZO4v2w1A7XFAYfygtvhewF1uNKrh9ui+T2nR81pPyQUOd8dz97jcY7ErskBoX7fxNMvh0nJdZw5Gs4HNNFpxC7g9OyN6ffRvGOVwcR6LLIfjSdB1R//IlO8qeNnkoQPu2gi4RzOPtzvlczdFL0tZ3VTXYA//v1LunK+OXPADgBDKlTn/k4RAjCtx9jFBSNvb4r+1/EN2wUMKHhjn7gdoLN8UPtaNRqTG76bL6Nf/cbErdAogBed0ArNGtYaG8lc+Gqa9g17d20hwDjWK+5zybeY89E3AKZK7DEzQpCX+3lyaxKtXtxnAu5wc6HrgvwNd0eWsYtiRu0p38cCniDxXTnrQzwC+kSkaxoWfL/mDMvntQ0j4ybNhaSSjs/N367f1l9pTeVFj56NeZn4bhznR30rT5E8YV4VpHEymVgJs6HDNWYzBLxcQgh2M3+LSYmj4HsWXCUrgHRxNQBUPj2rnwTngOFJzEx2QCM5ypcsYoC5zEeHrsGQOcrC8b5PiJ1VspZSb/TYqmFrCF+EaFeppyRbuNA7BMZSX5nKTLxS436X169EjpKq95D6f5nF7SnwHy6pEEgNW/RkBz8haTz2q5/EiGKYW9D60290dGjnreekAk1OVQugXjSjlxUmSibgIzBjVwrKML2I+HzBdGhApU="
       server:
         secure: "O1EDPLPU2O0DIdPU037C2SpaZLrjF8VK8b2AJuni+y1jZUIc3ExLK9MRaLRtQ+0Iot6rkBojYMISxrSHZykCZe4AkW3NsuMjMfZuGcxbybG6MdISieQvIMFZxRdxxletH3hGuUkgumQYQppFc1tcdhjCycl7cQFoN49wZUni0SbVBL6SHUg9J13YpWUrQSUa5l4BH9fNtxuvxKOsskVlIAeGWIqj1KJKfCzvOOsPKjaVL36ephWAFrE8P0kUb69KO+rsX25k7oyO9aptZu0bxc9DShveB3YPjAQYwzgM1QyJ7fFZ9h/C35TazRPaBEbTkJlU4QQtIsw88sOfvzKbZa9dYYyk2Rc1qjDLWHnYjdMipJwdfODmZqtUpG97940CdvsF0kH+E8c90CevS7C/VCTes+hqg6ajcTz81Je8kFgt+Au4vFPdJ199kZQyKoYbLYuPdwpQbPardI0wc9RhNDbLMA1Wqk6fodzhOISbvLPWvX+KMUHeGE2Gb935vVzVvfu2U3BLuuPu8IlB3GChq3cWaFKWTKSGRGV215k5DIfIBgbeXKxGmgD3z6ULSdu+7oXT3iVU0RSEsIScYQ0mcx8jGRtQf1IyLVRSeKPcwKxATRdIedVjGRVZDsouTpla5Bs94C9Ui3Ix0Wq0Q63dmYbbnButoYSxYyDqQ3kbqyY="
       skip_existing: true
       skip_cleanup: true
       on:
         tags: true
         all_branches: true
