language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -e tdvt/

script:
  - cd tdvt/test && python tdvt_test.py -v CommandLineTest ConfigTest DiffTest PrintConfigurationsTest
