language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  # - pip install -e tdvt/
  - pip install coveralls

script:
  - cd tdvt/test && coverage run -m tdvt_test.py -v CommandLineTest ConfigTest DiffTest PrintConfigurationsTest
  - coveralls
